import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const source = readFileSync(join(root, 'apps/pos-web/src/features/history/History.tsx'), 'utf8').replace(/\r\n/g, '\n');
const styles = readFileSync(join(root, 'apps/pos-web/src/App.css'), 'utf8').replace(/\r\n/g, '\n');

assert.match(source, /usePosSession/);
assert.match(source, /hasPermission\('orders\.reopen\.request'\)/);
assert.match(source, /hasPermission\('orders\.reopen\.authorize'\)/);
assert.match(source, /\/orders\/accounts\?/);
assert.match(source, /from_utc/);
assert.match(source, /to_utc/);
assert.match(source, /cash_shift_id/);
assert.match(source, /register_code/);
assert.match(source, /service_type/);
assert.match(source, /customer_label/);
assert.match(source, /next_cursor/);
assert.match(source, /loadAccounts\(nextCursor, true\)/);
assert.match(source, /localDayUtcBounds\(day, branchTimezone\)/);
assert.match(source, /search\.length >= 2/);
assert.match(source, /setTimeout\(\(\) => \{ void loadAccounts\(\); \}, 250\)/);
assert.match(source, /accountRequestSequence/);
assert.match(source, /sequence !== accountRequestSequence\.current/);
assert.match(source, /requestKeyRef/);
assert.match(source, /decisionKeysRef/);
assert.match(source, /Idempotency-Key/);
assert.match(source, /\/orders\/\$\{selected\.id\}\/reopen-requests/);
assert.match(source, /\/orders\/reopen-requests\?/);
assert.match(source, /\$\{request\.id\}\/\$\{decision\}/);
assert.match(source, /reason: reopenReason\.trim\(\)/);
assert.match(source, /evidence_refs: evidenceRefs/);
assert.match(source, /decision_reason: decisionReason\.trim\(\)/);
assert.match(source, /reopenReason\.trim\(\)\.length < 10/);
assert.match(source, /evidenceRefs\.length < 1 \|\| evidenceRefs\.length > 10/);
assert.match(source, /decisionReason\.trim\(\)\.length < 10/);
assert.match(source, /canRequestReopen && selected\.reopen_eligible && !selected\.active_reopen_request_status/);
assert.match(source, /requestKeyRef\.current = null; setReopenReason/);
assert.match(source, /decisionKeysRef\.current\.delete\(mapKey\);/);
assert.match(source, /Calidad del snapshot operativo/);
assert.match(source, /Solicitar reapertura/);
assert.match(source, /Solicitudes de reapertura/);
assert.match(source, /reopen-requests\/\$\{correctionRequest\.id\}\/apply/);
assert.match(source, /Editar y aplicar corrección/);
assert.match(source, /window\.confirm/);
assert.match(source, /openCorrectionEditor/);
assert.match(source, /correctionLines/);
assert.match(source, /source_line_id: line\.sourceLineId/);
assert.match(source, /product_id: line\.productId/);
assert.match(source, /production_dispositions/);
assert.match(source, /source_task_id: task\.id/);
assert.match(source, /task\.status === 'IN_PROGRESS'/);
assert.match(source, /settlement_method: correctionSettlementMethod/);
assert.match(source, /\.\.\.\(correctionSettlementMethod === 'cash' \? \{ register_id: configuredRegisterId \} : \{\}\)/);
assert.doesNotMatch(source, /register_id:\s*correctionSettlementMethod === 'cash' \? configuredRegisterId : null/);
assert.match(source, /correctionKeyRef/);
assert.match(source, /correctionSignature/);
assert.match(source, /correctionState === 'submitting'/);
assert.match(source, /correctionState === 'applied'/);
assert.match(source, /correctionCompletedReductions\.some\(\(\{ task \}\) => !correctionDispositions\[task\.id\]\)/);
assert.match(source, /<option value="" disabled>Selecciona una disposición<\/option>/);
assert.doesNotMatch(source, /disposition: correctionDispositions\[task\.id\] \|\| 'waste'/);
assert.match(source, /La imagen corregida está vacía: se solicitará al servidor una corrección total\./);
assert.doesNotMatch(source, /correctionLines\.length === 0\) \{ setCorrectionError/);
assert.match(source, /correctionKeyRef\.current = null;\n    setCorrectionState\('applied'\);/);
assert.match(source, /La corrección fue aplicada, pero no se pudo actualizar esta vista/);
assert.match(source, /corrections: Array<\{ id: string; request_id: string; folio: string; corrected_total_cents: number; settlement_delta_cents: number; currency: string; applied_at: string \}>/);
assert.match(source, /selected\.corrections\.map\(\(correction\) =>/);
assert.match(source, /Correcciones enlazadas/);
assert.match(source, /La venta original permanece sin cambios\./);
assert.match(source, /getCorrectionDeltaLabel\(correction\.settlement_delta_cents\)/);
assert.match(source, /Total corregido: \{formatCurrency\(correction\.corrected_total_cents\)\}/);
assert.match(source, /deltaCents > 0 \? 'Cargo adicional' : deltaCents < 0 \? 'Reembolso' : 'Conciliación sin diferencia'/);
assert.match(source, /No calcules ni captures diferencia; el backend la deriva\./);
assert.match(source, /La caja configurada se envía para validar el turno; el servidor sólo crea un movimiento si existe una diferencia\./);
assert.doesNotMatch(source, /corrected_total_cents\s*[+\-]/);
assert.doesNotMatch(source, /settlement_delta_cents\s*[+\-]/);
assert.match(styles, /grid-template-columns: repeat\(6, minmax\(0, 1fr\)\)/);
assert.match(styles, /@media \(max-width: 1100px\)[\s\S]*?\.orders-history-filters \{ grid-template-columns: repeat\(3, minmax\(0, 1fr\)\); \}/);
assert.match(styles, /\.orders-history-reopen-queue \{[\s\S]*?overflow: visible;[\s\S]*?background: #102a43 !important;[\s\S]*?color: #f8fafc;/);
assert.match(styles, /\.orders-history-reopen-queue h2,[\s\S]*?\.orders-history-reopen-queue strong,[\s\S]*?\.orders-history-reopen-queue span \{[\s\S]*?color: #f8fafc;/);
assert.match(styles, /\.orders-history-reopen-queue > p,[\s\S]*?\.orders-history-reopen-queue p,[\s\S]*?\.orders-history-reopen-queue label \{ color: #dbeafe; \}/);
assert.match(styles, /\.orders-history-reopen-queue textarea \{ color: #0f172a; background: #fff; \}/);
assert.match(styles, /\.orders-history-correction-lines \{ max-height: 290px; overflow: auto; \}/);
assert.match(styles, /\.orders-history-corrections \{ display: grid;/);
