import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const source = readFileSync('apps/pos-web/src/features/settings/userCashCuts.ts', 'utf8');
const view = readFileSync('apps/pos-web/src/features/settings/UserCashCutsPanel.tsx', 'utf8');
const settings = readFileSync('apps/pos-web/src/features/settings/Settings.tsx', 'utf8');
assert.match(source, /'loading' \| 'empty' \| 'ready' \| 'counting' \| 'finalizing' \| 'conflict' \| 'error'/);
assert.match(source, /exact\(value, keys\)/);
assert.match(source, /cash\.user_cut\.create/);
assert.match(source, /cash\.user_cut\.read/);
assert.match(source, /cash\.user_cut\.reopen\.request/);
assert.match(source, /cash\.user_cut\.reopen\.authorize/);
assert.match(source, /idempotency_conflict/);
assert.match(source, /Intl\.NumberFormat/);
assert.match(source, /parseUserCashCutCents/);
assert.match(source, /buildUserCashCutCreatePayload/);
assert.match(source, /buildUserCashCutCountedPayload/);
assert.match(source, /buildUserCashCutFinalizePayload/);
assert.match(source, /buildUserCashCutReopenRequestPayload/);
assert.match(source, /counted_cash_cents: countedCashCents, version/);
assert.match(source, /Object\.freeze\(\{ command, key, payload/);
assert.match(view, /status === 'OPERATIVELY_CLOSED'/);
assert.match(view, /!cutShiftIds\.has\(shift\.id\)/);
assert.match(view, /\/cash\/shifts\?\$\{params\}/);
assert.match(view, /\/cash\/shifts\/\$\{encodeURIComponent\(shiftId\)\}/);
assert.match(view, /next_cursor: string \| null/);
assert.match(view, /let cursor: string \| null = null/);
assert.match(view, /if \(cursor\) params\.set\('cursor', cursor\);/);
assert.match(view, /const seenCursors = new Set<string>\(\);/);
assert.match(view, /if \(seenCursors\.has\(page\.next_cursor\)\)/);
assert.match(view, /seenCursors\.add\(page\.next_cursor\);\s*cursor = page\.next_cursor;/s);
assert.match(view, /\} while \(cursor\);/);
assert.match(view, /const candidates = shifts\.filter/);
assert.match(view, /if \(!candidates\.length\) \{\s*setShiftMessage\('No hay turnos cerrados elegibles para esta caja\.'/s);
assert.match(view, /eligibleShiftLoadToken/);
assert.match(view, /eligibleShiftScope\.current\.branchId === scope\.branchId/);
assert.match(view, /'Idempotency-Key': intent\.key/);
assert.match(view, /Reintentar la misma solicitud/);
assert.match(view, /window\.confirm\('¿Confirmas el efectivo contado\?'/);
assert.match(view, /window\.confirm\('¿Confirmas finalizar este corte contado\?'/);
assert.match(view, /canReopenRequest/);
assert.match(view, /canReopenAuthorize/);
assert.match(settings, /cash\.user_cut\.reopen\.request/);
assert.match(settings, /cash\.user_cut\.reopen\.authorize/);
assert.match(view, /reopen-request/);
assert.match(view, /reopen-approve/);
assert.match(view, /reopen-reject/);
assert.match(view, /reopen-compensate/);
assert.match(view, /\/reopen-requests/);
assert.match(view, /buildUserCashCutReopenRequestPayload\(cents, reopenReason, evidenceRefs\)/);
assert.match(view, /setReopenIntent\(null\)/);
assert.match(view, /setSelected\(null\);\s*setItems\(\[\]\);\s*setCursor\(null\);/s);
assert.match(view, /if \(countIntent\) setCountIntent\(null\)/);
assert.match(view, /window\.confirm\('¿Confirmas solicitar la reapertura del corte\?'/);
assert.match(view, /window\.confirm\(decision === 'approve'/);
assert.match(view, /window\.confirm\('¿Confirmas registrar la compensación de reapertura\?'/);
assert.match(view, /type CutCommandIntent<T>[\s\S]*cutId: string/);
assert.match(view, /cutId: cut\.id/);
assert.match(view, /const runCount = async \(intent:[\s\S]*encodeURIComponent\(intent\.cutId\).*counted-cash/s);
assert.match(view, /const runFinalize = async \(intent:[\s\S]*encodeURIComponent\(intent\.cutId\).*finalize/s);
assert.match(view, /else if \(countIntent\) void runCount\(countIntent\);/);
assert.match(view, /else if \(finalizeIntent\) void runFinalize\(finalizeIntent\);/);
assert.doesNotMatch(view, /runCount\(countIntent, parseUserCashCut\(selected\.cash_cut\)\.id\)/);
assert.doesNotMatch(view, /runFinalize\(finalizeIntent, parseUserCashCut\(selected\.cash_cut\)\.id\)/);
assert.match(view, /if \(countIntent && countIntent\.cutId !== id\) setCountIntent\(null\);/);
assert.match(view, /if \(finalizeIntent && finalizeIntent\.cutId !== id\) setFinalizeIntent\(null\);/);
assert.match(view, /detail\.reopen === null\s*\|\| detail\.reopen\.status === 'REJECTED'\s*\|\| detail\.reopen\.status === 'COMPENSATED'/);
assert.match(view, /Intl\.DateTimeFormat\('es-MX', \{[\s\S]*timeZone,/);
assert.match(view, /catch \{\s*return 'Fecha no disponible';\s*\}/);
assert.match(view, /cut\.register_code_snapshot/);
assert.match(view, /cut\.cashier_user_id/);
assert.match(view, /cut\.timezone/);
assert.match(view, /formatCashCutSnapshotTime\(cut\.period_start, cut\.timezone\)/);
assert.match(view, /formatCashCutSnapshotTime\(cut\.period_end, cut\.timezone\)/);
assert.doesNotMatch(view, /detail\.reopen\.(reason|evidence_refs)/);
assert.doesNotMatch(source, /expected_cash_cents\s*[=+\-]/);
assert.doesNotMatch(source, /difference_cents\s*[=+\-]/);
assert.doesNotMatch(source, /difference_delta_cents\s*[=+\-]/);
assert.doesNotMatch(view, /expected_cash_cents\s*[=+\-]/);
assert.doesNotMatch(view, /difference_cents\s*[=+\-]/);
assert.doesNotMatch(view, /difference_delta_cents\s*[=+\-]/);
console.log('POS user cash cuts semantic contract passed');
