import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const source = readFileSync(join(root, 'apps/pos-web/src/features/history/History.tsx'), 'utf8');
const styles = readFileSync(join(root, 'apps/pos-web/src/App.css'), 'utf8');

assert.match(source, /usePosSession/);
assert.match(source, /hasPermission\('orders\.reopen\.request'\)/);
assert.match(source, /hasPermission\('orders\.reopen\.authorize'\)/);
assert.match(source, /\/orders\/accounts\?/);
assert.match(source, /from_utc/);
assert.match(source, /to_utc/);
assert.match(source, /cash_shift_id/);
assert.match(source, /register_code/);
assert.match(source, /service_type/);
assert.match(source, /customer_label/);
assert.match(source, /next_cursor/);
assert.match(source, /loadAccounts\(nextCursor, true\)/);
assert.match(source, /localDayUtcBounds\(day, branchTimezone\)/);
assert.match(source, /search\.length >= 2/);
assert.match(source, /setTimeout\(\(\) => \{ void loadAccounts\(\); \}, 250\)/);
assert.match(source, /accountRequestSequence/);
assert.match(source, /sequence !== accountRequestSequence\.current/);
assert.match(source, /requestKeyRef/);
assert.match(source, /decisionKeysRef/);
assert.match(source, /Idempotency-Key/);
assert.match(source, /\/orders\/\$\{selected\.id\}\/reopen-requests/);
assert.match(source, /\/orders\/reopen-requests\?/);
assert.match(source, /\$\{request\.id\}\/\$\{decision\}/);
assert.match(source, /reason: reopenReason\.trim\(\)/);
assert.match(source, /evidence_refs: evidenceRefs/);
assert.match(source, /decision_reason: decisionReason\.trim\(\)/);
assert.match(source, /reopenReason\.trim\(\)\.length < 10/);
assert.match(source, /evidenceRefs\.length < 1 \|\| evidenceRefs\.length > 10/);
assert.match(source, /decisionReason\.trim\(\)\.length < 10/);
assert.match(source, /canRequestReopen && selected\.reopen_eligible && !selected\.active_reopen_request_status/);
assert.match(source, /requestKeyRef\.current = null; setReopenReason/);
assert.match(source, /decisionKeysRef\.current\.delete\(mapKey\);/);
assert.match(source, /Calidad del snapshot operativo/);
assert.match(source, /Solicitar reapertura/);
assert.match(source, /Solicitudes de reapertura/);
assert.doesNotMatch(source, /reopen-requests\/\$\{[^}]+\}\/apply/);
assert.doesNotMatch(source, /apply_order_reopen_request/);
assert.match(styles, /grid-template-columns: repeat\(6, minmax\(0, 1fr\)\)/);
assert.match(styles, /@media \(max-width: 1100px\)[\s\S]*?\.orders-history-filters \{ grid-template-columns: repeat\(3, minmax\(0, 1fr\)\); \}/);
assert.match(styles, /\.orders-history-reopen-queue \{[\s\S]*?overflow: visible;[\s\S]*?background: #102a43 !important;[\s\S]*?color: #f8fafc;/);
assert.match(styles, /\.orders-history-reopen-queue h2,[\s\S]*?\.orders-history-reopen-queue strong,[\s\S]*?\.orders-history-reopen-queue span \{[\s\S]*?color: #f8fafc;/);
assert.match(styles, /\.orders-history-reopen-queue > p,[\s\S]*?\.orders-history-reopen-queue p,[\s\S]*?\.orders-history-reopen-queue label \{ color: #dbeafe; \}/);
assert.match(styles, /\.orders-history-reopen-queue textarea \{ color: #0f172a; background: #fff; \}/);
