import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const recipe = readFileSync('apps/admin-web/src/features/catalog/RecipeManager.tsx', 'utf8');
const workspace = readFileSync('apps/admin-web/src/features/recipes/RecipesWorkspace.tsx', 'utf8');
const app = readFileSync('apps/admin-web/src/App.tsx', 'utf8');
const products = readFileSync('apps/admin-web/src/features/catalog/ProductsList.tsx', 'utf8');
assert.match(recipe, /'Idempotency-Key': intentKey\.current/);
assert.match(recipe, /expected_active_recipe_id: recipe\?\.id \|\| null/);
assert.match(recipe, /branch_id: branchId/);
assert.match(recipe, /recipe_version_conflict/);
assert.match(recipe, /La receta cambió en otra sesión/);
assert.doesNotMatch(recipe, /fetchApi\('\/inventory\/items'\)/);
assert.doesNotMatch(recipe, /localStorage\.getItem\('active_branch_id'\)/);
assert.match(workspace, /\/recipes\/workspace/);
assert.match(workspace, /corporate_allowed/);
assert.match(workspace, /Editar receta/);
assert.match(workspace, /color: '#111827'/);
assert.match(workspace, /background: '#fff'/);
assert.match(app, /permissions\.includes\('recipes\.manage'\)/);
assert.match(app, /path="recipes"/);
assert.match(app, /RecipesManageRoute/);
assert.doesNotMatch(products, /RecipeManager/);
assert.doesNotMatch(workspace, /branch_id=\$\{encodeURIComponent\(scope \|\| ''\)\}/);
assert.match(workspace, /useState<string \| null>\(\(\) => resolveBranchId\(\) \|\| null\)/);
assert.match(workspace, /scope === null \? ''/);
assert.match(workspace, /event\.target\.value === '' \? null : event\.target\.value/);
assert.doesNotMatch(workspace, /scope \?\? workspace\?\.selected_branch_id/);
assert.doesNotMatch(workspace, /enabled: scope !== undefined/);
console.log('PCO-007 recipe semantic contract passed');
