// SEC001-SYNTHETIC-FIXTURE provenance=restaurantos-catalog-classification-browser-v1
import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
const { chromium } = await import(process.env.ADMINRETRO_PLAYWRIGHT_IMPORT || 'playwright');
const adminUrl = process.env.ADMINRETRO_BASE_URL || 'http://127.0.0.1:3002/admin';
const posUrl = process.env.CATCLASS_POS_URL || 'http://127.0.0.1:3001/pos';
const output = resolve('output/playwright/catalog-classification');
mkdirSync(output, { recursive: true });
const branch = '018f6f73-2d0a-74f0-8f1c-000000000003';
const metadata = { catalog_classification_mode: 'explicit', catalog_generation: 1, catalog_hash: 'synthetic-catalog-hash-1', catalog_projection_hash: 'synthetic-projection-1' };
let activePage;
const browser = await chromium.launch({ headless: true, ...(process.env.ADMINRETRO_CHROME_PATH ? { executablePath: process.env.ADMINRETRO_CHROME_PATH } : {}) });
try {
  for (const viewport of [{ width: 1440, height: 1000 }, { width: 390, height: 844 }]) {
    const label = viewport.width === 390 ? 'mobile' : 'desktop';
    const page = await browser.newPage({ viewport });
    activePage = page;
    page.setDefaultTimeout(30000);
    page.setDefaultNavigationTimeout(60000);
    const errors = [];
    page.on('pageerror', (error) => { errors.push(error.message); console.error('PAGE ERROR', error.message); });
    const groups = [{ id: 'food-group', name: 'ALIMENTOS BARRA', display_order: 1, status: 'active', classification_code: 'food', configuration_version: 2 }, { id: 'beer-group', name: 'CERVEZAS', display_order: 2, status: 'active', classification_code: 'drinks', configuration_version: 1 }];
    const products = [{ id: 'food-product', name: 'ALIMENTO EN BARRA', sku: 'FOOD-QA', category_id: 'food-group', category_name: 'ALIMENTOS BARRA', station: 'drinks', price_cents: 3000, status: 'active', catalog_scope: 'organization', classification_code: 'food', ...metadata }, { id: 'beer-product', name: 'CERVEZA ARTESANAL', sku: 'BEER-QA', category_id: 'beer-group', category_name: 'CERVEZAS', station: 'kitchen', price_cents: 5000, status: 'active', catalog_scope: 'organization', classification_code: 'drinks', ...metadata }];
    const writes = [];
    let nextFailure = 409;
    let invalidSelection = false;
    let initialLegacy = false;
    let productsUnavailable = true;
    const initialMetadata = { catalog_classification_mode: 'legacy', catalog_generation: 0, catalog_hash: '', catalog_projection_hash: 'initial-legacy' };
    await page.addInitScript(({ branch }) => {
      localStorage.setItem('auth_token', 'synthetic-classification-token');
      localStorage.setItem('admin_branch_id', branch);
      localStorage.setItem('user', JSON.stringify({ id: 'classification-qa', display_name: 'QA', is_superadmin: true, assigned_branch_id: branch, roles: ['Administrador'], permissions: ['catalog.manage', 'orders.create'] }));
    }, { branch });
    await page.route('**/api/v1/**', async (route) => {
      const request = route.request();
      const url = new URL(request.url());
      const path = url.pathname.replace('/api/v1', '');
      if (path === '/auth/session') return route.fulfill({ json: { user: { id: 'qa', display_name: 'QA', status: 'active' }, roles: [], permissions: ['orders.create', 'pos.operate'], scope: { level: 'branch', assigned_branch_id: branch, allowed_branch_ids: [branch] }, active_branch: { id: branch, name: 'Sucursal QA', code: 'QA', timezone: 'UTC', status: 'active', business_unit: { id: 'bu', name: 'QA', code: 'QA', unit_type: 'store' }, legal_entity: { id: 'le', name: 'QA' }, warehouse: null } } });
      if (path === '/branches') return route.fulfill({ json: [{ id: branch, name: 'Sucursal QA', status: 'active' }] });
      if (path === '/categories' && request.method() === 'GET') return route.fulfill({ json: url.searchParams.has('branch_id') ? groups.map((group) => ({ ...group, ...(initialLegacy ? initialMetadata : metadata) })) : groups });
      if (path.startsWith('/categories') && ['PUT', 'POST'].includes(request.method())) {
        const body = request.postDataJSON();
        writes.push({ path, body, key: request.headers()['idempotency-key'] });
        if (nextFailure) { const status = nextFailure; nextFailure = 0; return route.fulfill({ status, json: { detail: { code: status === 409 ? 'category_version_conflict' : 'temporary_failure', message: 'Fallo sintético' } } }); }
        const current = request.method() === 'PUT' ? groups.find((group) => path.endsWith(group.id)) : null;
        const saved = { ...body, id: current?.id || `group-${groups.length}`, status: body.status || 'active', configuration_version: (current?.configuration_version || 0) + 1 };
        delete saved.expected_version;
        if (current) Object.assign(current, saved); else groups.push(saved);
        return route.fulfill({ json: saved });
      }
      if (path.endsWith('/selection-group')) return route.fulfill({ json: { category_id: path.split('/')[2], group: null, values: [], products: [], incomplete_products: [], complete: true } });
      if (path === '/catalog/products' && productsUnavailable) return route.fulfill({ status: 503, json: { detail: { message: 'Catálogo temporalmente no disponible' } } });
      if (path === '/catalog/products') return route.fulfill({ json: invalidSelection && url.searchParams.has('branch_id') ? products.map((product, index) => index === 0 ? { ...product, selection: { group_id: 'stale', value_id: 'foreign' } } : product) : initialLegacy && url.searchParams.has('branch_id') ? products.map((product) => ({ ...product, ...initialMetadata })) : products });
      if (path.endsWith('/quote')) return route.fulfill({ json: { schema_version: 'order-quote.v1', branch_id: branch, currency: 'MXN', lines: [], subtotal_cents: 3000, adjustment_cents: 0, tax_cents: null, total_cents: 3000 } });
      return route.fulfill({ json: [] });
    });
    console.log(`Opening groups ${label}`);
    await page.goto(`${adminUrl}/categories`, { waitUntil: 'domcontentloaded' });
    await page.getByLabel('Clasificación comercial', { exact: true }).waitFor();
    await page.getByLabel('Nombre del grupo', { exact: true }).fill('ALIMENTOS BORRADOR');
    await page.getByLabel('Clasificación comercial', { exact: true }).selectOption('other');
    await page.getByRole('button', { name: 'Guardar grupo', exact: true }).click();
    await page.getByRole('alert').filter({ hasText: 'borrador se conserva' }).waitFor();
    assert.equal(await page.getByLabel('Nombre del grupo', { exact: true }).inputValue(), 'ALIMENTOS BORRADOR');
    assert.equal(writes[0].body.expected_version, 2);
    assert.equal(writes[0].body.classification_code, 'other');
    assert.ok(writes[0].key);
    await page.getByRole('button', { name: 'Descartar borrador y cargar versión vigente' }).click();
    await page.getByText('Versión vigente cargada.', { exact: false }).waitFor();
    assert.equal(await page.getByLabel('Nombre del grupo', { exact: true }).inputValue(), 'ALIMENTOS BARRA');
    nextFailure = 503;
    await page.getByRole('button', { name: 'Guardar grupo', exact: true }).click();
    await page.getByRole('alert').filter({ hasText: 'Fallo sintético' }).waitFor();
    await page.getByRole('button', { name: 'Guardar grupo', exact: true }).click();
    await page.getByText('Grupo actualizado.', { exact: true }).waitFor();
    assert.equal(writes[1].key, writes[2].key, 'retry key must be stable');
    await page.getByRole('button', { name: 'Nuevo grupo', exact: true }).click();
    await page.getByLabel('Nombre del grupo', { exact: true }).fill('GRUPO NORMAL QA');
    assert.equal(await page.getByRole('button', { name: 'Guardar grupo', exact: true }).isDisabled(), true);
    await page.getByLabel('Clasificación comercial', { exact: true }).selectOption('other');
    await page.getByRole('button', { name: 'Guardar grupo', exact: true }).focus();
    await page.keyboard.press('Enter');
    await page.getByText('Grupo creado.', { exact: true }).waitFor();
    assert.equal(writes.at(-1).body.expected_version, 0);
    assert.equal(writes.at(-1).body.classification_code, 'other');
    await page.getByLabel('Clasificación comercial', { exact: true }).scrollIntoViewIfNeeded();
    await page.screenshot({ path: `${output}/groups-${label}.png`, fullPage: true });
    console.log(`Opening products ${label}`);
    await page.goto(`${adminUrl}/products`, { waitUntil: 'domcontentloaded' });
    await page.getByRole('alert').filter({ hasText: 'No se pudo cargar el catálogo' }).waitFor();
    assert.equal(await page.getByText('No hay productos registrados.', { exact: true }).count(), 0);
    productsUnavailable = false;
    await page.getByRole('button', { name: 'Reintentar productos', exact: true }).click();
    await page.getByRole('cell', { name: 'ALIMENTO EN BARRA', exact: true }).waitFor();
    await page.getByRole('button', { name: 'Contraer menú lateral', exact: true }).click();
    await page.reload({ waitUntil: 'domcontentloaded' });
    await page.getByRole('button', { name: 'Expandir menú lateral', exact: true }).press('Enter');
    await page.getByRole('button', { name: 'Contraer menú lateral', exact: true }).waitFor();
    await page.getByPlaceholder('Buscar clave o descripción...').fill('NO COINCIDE QA');
    await page.getByText('No hay productos que coincidan con los filtros.', { exact: true }).waitFor();
    await page.getByPlaceholder('Buscar clave o descripción...').fill('');
    const inherited = page.getByLabel('Clasificación heredada del grupo');
    await inherited.waitFor();
    console.log(`Products loaded ${label}`);
    await page.getByRole('cell', { name: 'ALIMENTO EN BARRA', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#product-inherited-classification')?.value === 'Alimentos');
    assert.equal(await inherited.inputValue(), 'Alimentos');
    assert.equal(await inherited.getAttribute('readonly'), '');
    await page.getByRole('button', { name: 'Editar', exact: true }).click();
    await page.getByLabel('Crear grupo sin salir del producto').click();
    console.log(`Quick-create open ${label}`);
    const dialog = page.getByRole('dialog', { name: 'Nuevo grupo' });
    await dialog.getByLabel('Nombre del grupo').fill('GRUPO CONTEXTUAL QA');
    assert.equal(await dialog.getByRole('button', { name: 'Crear grupo', exact: true }).isDisabled(), true);
    await dialog.getByLabel('Clasificación comercial').selectOption('drinks');
    nextFailure = 503;
    await dialog.getByRole('button', { name: 'Crear grupo', exact: true }).click();
    await dialog.getByRole('alert').waitFor();
    assert.equal(await dialog.getByLabel('Nombre del grupo').inputValue(), 'GRUPO CONTEXTUAL QA');
    const attempted = writes.at(-1);
    await dialog.getByRole('button', { name: 'Crear grupo', exact: true }).click();
    await dialog.waitFor({ state: 'hidden' });
    assert.equal(writes.at(-1).key, attempted.key);
    assert.equal(writes.at(-1).body.classification_code, 'drinks');
    assert.equal(await inherited.inputValue(), 'Bebidas');
    await inherited.scrollIntoViewIfNeeded();
    await page.screenshot({ path: `${output}/product-${label}.png`, fullPage: true });
    // The POS mock is a separate canonical snapshot: restore groups used by the products.
    groups[0].classification_code = 'food';
    console.log(`Opening POS ${label}`);
    await page.goto(`${posUrl}/`, { waitUntil: 'domcontentloaded' });
    await page.getByRole('navigation', { name: 'Grupos del menú' }).waitFor();
    await page.getByRole('button', { name: 'ALIMENTOS', exact: true }).click();
    const foodGroups = page.getByRole('region', { name: 'Grupos de ALIMENTOS' });
    await foodGroups.waitFor();
    assert.equal(await foodGroups.getByText('CERVEZAS', { exact: true }).count(), 0);
    await foodGroups.getByText('ALIMENTOS BARRA', { exact: true }).click();
    await page.getByRole('region', { name: 'Productos disponibles' }).getByText('ALIMENTO EN BARRA', { exact: true }).waitFor();
    assert.equal(await page.getByRole('region', { name: 'Productos disponibles' }).getByText('CERVEZA ARTESANAL', { exact: true }).count(), 0);
    await page.getByLabel('Agregar ALIMENTO EN BARRA a favoritos').click();
    await page.getByRole('button', { name: 'FAVORITOS', exact: true }).click();
    await page.getByRole('region', { name: 'Productos disponibles' }).getByText('ALIMENTO EN BARRA', { exact: true }).waitFor();
    await page.getByPlaceholder('Buscar producto…').fill('ALIMENTO');
    await page.screenshot({ path: `${output}/pos-${label}.png`, fullPage: true });
    invalidSelection = true;
    await page.reload({ waitUntil: 'domcontentloaded' });
    await page.getByRole('alert').filter({ hasText: 'menú coherente' }).waitFor();
    invalidSelection = false;
    await page.getByRole('button', { name: 'Reintentar', exact: true }).click();
    await page.getByRole('region', { name: 'Grupos de TODO' }).waitFor();
    initialLegacy = true;
    await page.reload({ waitUntil: 'domcontentloaded' });
    await page.getByRole('button', { name: 'BEBIDAS', exact: true }).click();
    await page.getByRole('region', { name: 'Grupos de BEBIDAS' }).getByText('ALIMENTOS BARRA', { exact: true }).waitFor();
    assert.deepEqual(errors, []);
    console.log(`CAT-CLASS browser ${label}: normal/contextual create, required classification, CAS conflict, stable retries, inherited label, explicit POS and favorites passed`);
    await page.close();
  }
} catch (error) { console.error(error); console.error('BODY', await activePage?.locator('body').innerText()); process.exitCode = 1; } finally { await browser.close(); }
process.exit(process.exitCode || 0);
