import React, { useEffect, useMemo, useState } from 'react';
import { AlertCircle, Plus, Search } from 'lucide-react';
import { fetchApi, ApiError } from '@restaurantos/api-client';
import { usePosSession } from '../../session';
import { BranchAdminPage } from './BranchAdminPage';

interface Extra { product_id: string; product_name: string; option_id: string; name: string; central_status: string; effective_enabled: boolean; override: boolean | null; inventory_item_name: string; inventory_item_sku?: string | null; unit_code?: string | null; effect_type: 'add'; }

/** Supervisors can only set branch availability for canonical add-only extras. */
export default function BranchAdminIngredientExtras() {
  const { hasPermission, session } = usePosSession(); const [extras, setExtras] = useState<Extra[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [acting, setActing] = useState<string | null>(null); const canManage = hasPermission('catalog.branch.manage');
  const load = async () => { setLoading(true); setError(''); try { setExtras(await fetchApi<Extra[]>('/branch-administration/catalog/ingredient-variations')); } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'No fue posible cargar los ingredientes adicionales.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const visible = useMemo(() => { const query = search.trim().toLowerCase(); return !query ? extras : extras.filter((extra) => `${extra.product_name} ${extra.name} ${extra.inventory_item_name} ${extra.inventory_item_sku || ''}`.toLowerCase().includes(query)); }, [extras, search]);
  const setAvailability = async (optionId: string, action: 'available' | 'unavailable' | 'inherit') => { setActing(optionId); setError(''); try { await fetchApi(`/branch-administration/catalog/ingredient-variations/${encodeURIComponent(optionId)}`, { method: 'PUT', body: JSON.stringify({ action }) }); await load(); } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'No fue posible actualizar la disponibilidad.'); } finally { setActing(null); } };
  return <BranchAdminPage title="Ingredientes adicionales" description={`Disponibilidad local de porciones extra${session?.active_branch?.name ? ` · ${session.active_branch.name}` : ''}.`} icon={Plus}>
    <p style={{ color: '#64748b' }}>El catálogo, cantidades, insumo y precio los administra corporativo.</p><div style={{ position: 'relative', maxWidth: 440, marginBottom: 16 }}><Search size={16} style={{ position: 'absolute', left: 10, top: 11, color: '#64748b' }} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar por insumo o producto…" style={{ width: '100%', boxSizing: 'border-box', padding: '9px 12px 9px 32px', border: '1px solid #cbd5e1', borderRadius: 8 }} /></div>
    {error && <div role="alert" style={{ color: '#b91c1c', display: 'flex', gap: 6, alignItems: 'center' }}><AlertCircle size={16} />{error} <button onClick={() => void load()}>Reintentar</button></div>}{loading ? <p>Cargando ingredientes adicionales…</p> : visible.length === 0 ? <p style={{ color: '#64748b' }}>No hay ingredientes adicionales disponibles.</p> : <div style={{ display: 'grid', gap: 8 }}>{visible.map((extra) => <div key={extra.option_id} style={{ padding: 12, background: '#fff', border: '1px solid #e2e8f0', borderRadius: 10, display: 'flex', gap: 10, alignItems: 'center', flexWrap: 'wrap' }}><div style={{ flex: 1 }}><strong>{extra.name}</strong><div style={{ fontSize: 12, color: '#64748b' }}>{extra.inventory_item_name} {extra.inventory_item_sku ? `· ${extra.inventory_item_sku}` : ''} {extra.unit_code ? `· ${extra.unit_code}` : ''} · {extra.product_name} · Central: {extra.central_status}</div></div><span style={{ color: extra.effective_enabled ? '#047857' : '#b91c1c', fontSize: 13 }}>{extra.effective_enabled ? 'Disponible' : 'No disponible'}</span>{canManage && <div style={{ display: 'flex', gap: 6 }}><button disabled={acting === extra.option_id} onClick={() => void setAvailability(extra.option_id, 'available')}>Disponible</button><button disabled={acting === extra.option_id} onClick={() => void setAvailability(extra.option_id, 'unavailable')}>No disponible</button><button disabled={acting === extra.option_id} onClick={() => void setAvailability(extra.option_id, 'inherit')}>Heredar</button></div>}</div>)}</div>}
  </BranchAdminPage>;
}
